AllCops:
  NewCops: enable
  SuggestExtensions: false

Lint/DuplicateMethods:
  Exclude:
    - lib/gvltools.rb # we need the self alias trick to avoid warnings

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/GlobalVars:
  Exclude:
    - ext/**/extconf.rb

Style/EmptyMethod:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
